//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factuurregel
    {
        public string factuurnummer { get; set; }
        public string kenteken { get; set; }
        public System.DateTime begindatum { get; set; }
        public System.DateTime einddatum { get; set; }
        public Nullable<decimal> dagprijs { get; set; }
        public Nullable<decimal> totaal { get; set; }
    
        public virtual auto auto { get; set; }
        public virtual factuur factuur { get; set; }
    }
}
