//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factuur
    {
		internal object klant;
		internal object medewerker;

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factuur()
        {
            this.factuurregel = new HashSet<factuurregel>();
        }
    
        public string factuurnummer { get; set; }
        public string klantcode { get; set; }
        public string medewerkerscode { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<decimal> factuurtotaal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factuurregel> factuurregel { get; set; }
    }
}
