//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class klant
    {
        public string klantcode { get; set; }
        public string voorletters { get; set; }
        public string tussenvoegsels { get; set; }
        public string achternaam { get; set; }
        public string adres { get; set; }
        public string postcode { get; set; }
        public string woonplaats { get; set; }
        public string gebruikersnaam { get; set; }
        public string wachtwoord { get; set; }
        public string medewerker { get; set; }
        public string naam { get; set; }
    
        public virtual medewerker medewerker1 { get; set; }
    }
}
